---
- hosts: "target_servers"
  become: yes
  become_method: sudo
  vars:
    users:
    -  "paul"
    - "tanya"
    - "ruby"
  tasks:
  - name: "Create user accounts"
    user:
      name: "{{ item }}"
      groups: "ansible"
    with_items: "{{ users }}"
  - name: "Add authorized keys"
    authorized_key:
      user: "{{ item }}"
      key: "{{ lookup('file', 'files/'+ item + '.key.pub') }}"
    with_items: "{{ users }}"
  - name: "Allow admin users to sudo without a password"
    lineinfile:
      dest: "/etc/sudoers" # path: in version 2.3
      state: "present"
      regexp: "^%wheel"
      line: "%wheel ALL=(ALL) NOPASSWD: ALL"
